const inventoryData = [
  {
    name: "BINDER CLIPS UK.105",
    category: "ATK",
    stock_awal: 7,
    stock_in: 48,
    stock_out: 46,
    stock_akhir: 9,
    satuan: "PAK",
    min_stock: 7,
  },
  {
    name: "BINDER CLIPS UK.111",
    category: "ATK",
    stock_awal: 11,
    stock_in: 0,
    stock_out: 0,
    stock_akhir: 11,
    satuan: "PAK",
    min_stock: 7,
  },
  {
    name: "BINDER CLIPS UK.200",
    category: "ATK",
    stock_awal: 1,
    stock_in: 18,
    stock_out: 16,
    stock_akhir: 3,
    satuan: "PAK",
    min_stock: 7,
  },
  {
    name: "BOLPOINT BIRU",
    category: "ATK",
    stock_awal: 15,
    stock_in: 0,
    stock_out: 2,
    stock_akhir: 13,
    satuan: "PAK",
    min_stock: 7,
  },
  {
    name: "KERTAS HVS F4",
    category: "ATK",
    stock_awal: 40,
    stock_in: 280,
    stock_out: 329,
    stock_akhir: -9,
    satuan: "RIM",
    min_stock: 7,
  },
  {
    name: "KERTAS TIMBANGAN",
    category: "ATK",
    stock_awal: 21,
    stock_in: 20,
    stock_out: 20,
    stock_akhir: 21,
    satuan: "ROLL",
    min_stock: 7,
  },
  {
    name: "LAKBAN SN",
    category: "ATK",
    stock_awal: 10,
    stock_in: 77,
    stock_out: 69,
    stock_akhir: 18,
    satuan: "DOS",
    min_stock: 7,
  },
  {
    name: "PAPER FASTENER",
    category: "ATK",
    stock_awal: 5,
    stock_in: 9,
    stock_out: 9,
    stock_akhir: 5,
    satuan: "PAK",
    min_stock: 7,
  },
  {
    name: "STABILO KUNING",
    category: "ATK",
    stock_awal: 2,
    stock_in: 6,
    stock_out: 7,
    stock_akhir: 1,
    satuan: "PCS",
    min_stock: 7,
  },
  {
    name: "PENGGARIS BESI",
    category: "ATK",
    stock_awal: 12,
    stock_in: 10,
    stock_out: 5,
    stock_akhir: 17,
    satuan: "PCS",
    min_stock: 7,
  },
  {
    name: "PENGHAPUS PUTIH",
    category: "ATK",
    stock_awal: 8,
    stock_in: 3,
    stock_out: 2,
    stock_akhir: 9,
    satuan: "PCS",
    min_stock: 7,
  },
  {
    name: "SPIDOL PERMANEN",
    category: "ATK",
    stock_awal: 6,
    stock_in: 10,
    stock_out: 4,
    stock_akhir: 12,
    satuan: "PCS",
    min_stock: 7,
  },
  {
    name: "MAP KERTAS",
    category: "ATK",
    stock_awal: 15,
    stock_in: 5,
    stock_out: 10,
    stock_akhir: 10,
    satuan: "PCS",
    min_stock: 7,
  },
  {
    name: "KERTAS STIKER",
    category: "ATK",
    stock_awal: 3,
    stock_in: 10,
    stock_out: 6,
    stock_akhir: 7,
    satuan: "RIM",
    min_stock: 7,
  },
  {
    name: "KERTAS WARNA",
    category: "ATK",
    stock_awal: 10,
    stock_in: 2,
    stock_out: 5,
    stock_akhir: 7,
    satuan: "RIM",
    min_stock: 7,
  },
  {
    name: "KLIP KERTAS",
    category: "ATK",
    stock_awal: 9,
    stock_in: 10,
    stock_out: 12,
    stock_akhir: 7,
    satuan: "PCS",
    min_stock: 7,
  },
  {
    name: "KAPUR TULIS",
    category: "ATK",
    stock_awal: 20,
    stock_in: 10,
    stock_out: 15,
    stock_akhir: 15,
    satuan: "PAK",
    min_stock: 7,
  },
  {
    name: "SPIRAL BINDER",
    category: "ATK",
    stock_awal: 2,
    stock_in: 2,
    stock_out: 0,
    stock_akhir: 4,
    satuan: "PCS",
    min_stock: 7,
  },
  {
    name: "CORRECTION TAPE",
    category: "ATK",
    stock_awal: 1,
    stock_in: 10,
    stock_out: 5,
    stock_akhir: 6,
    satuan: "PCS",
    min_stock: 7,
  },
  {
    name: "KALKULATOR MINI",
    category: "ATK",
    stock_awal: 3,
    stock_in: 3,
    stock_out: 1,
    stock_akhir: 5,
    satuan: "PCS",
    min_stock: 7,
  },
];

export async function GET() {
  return Response.json(inventoryData);
}